Repository Nasirkhan294/final-capstone-back-end, pull requests merged in 2023-09, with the labels that each got.

#12 Setup: changes
  .gitattributes
  .github/workflows/linters.yml
  .gitignore
  .rubocop.yml
  .ruby-version
  .stylelintrc.json
  Gemfile
  Gemfile.lock
  Rakefile
  RooMic_ER_Diagram.png
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/concerns/.keep
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  bin/bundle
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/storage.yml
  db/seeds.rb
  lib/tasks/.keep
  log/.keep
  public/robots.txt
  storage/.keep
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/files/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/test_helper.rb
  tmp/.keep
  tmp/pids/.keep
  tmp/storage/.keep
  vendor/.keep
Labels: enhancement

#13 Models
  .rspec
  Gemfile
  Gemfile.lock
  app/models/reservation.rb
  app/models/room.rb
  app/models/user.rb
  db/migrate/20230922064147_create_users.rb
  db/migrate/20230922065453_create_rooms.rb
  db/migrate/20230922073346_create_reservations.rb
  db/schema.rb
  db/seeds.rb
  spec/models/reservation_spec.rb
  spec/models/room_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/fixtures/reservations.yml
  test/fixtures/rooms.yml
  test/fixtures/users.yml
  test/models/reservation_test.rb
  test/models/room_test.rb
  test/models/user_test.rb
Labels: enhancement

#15 Api controllers: changes
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/models/room.rb
  app/models/user.rb
  config/routes.rb
  spec/requests/api/v1/reservations_spec.rb
  spec/requests/api/v1/rooms_spec.rb
  spec/requests/api/v1/users_spec.rb
Labels: enhancement, good first issue

#16 Authorization: changes
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/api/v1/users/registrations_controller.rb
  app/controllers/api/v1/users/sessions_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/rack_session_fix.rb
  app/models/user.rb
  app/serializers/user_serializer.rb
  config/credentials.yml.enc
  config/environments/development.rb
  config/initializers/cors.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/puma.rb
  config/routes.rb
  db/migrate/20230926122317_add_devise_to_users.rb
  db/migrate/20230926124622_add_jti_to_users.rb
  db/schema.rb
  spec/requests/api/v1/reservations_spec.rb
  spec/requests/api/v1/users_spec.rb
Labels: bug, documentation, enhancement
